### ISSUE TITLE
Jasmine engine support

### ISSUE THREAD

**Issue by hackerunet** [ForceUniverse/dart-force#31]
Hello, I personallly don't like using mustache as view rendering engine, however I would like to know if this framework supports jasmine. does it?

**Comment by hackerunet** [comment]
This project is dead. sorry.

**Comment by jorishermans** [comment]
It is very sad to see that somebody has a comment about a project and don't want to commit to this project. It is open source, so I am always open to accept pull requests.

**Comment by jorishermans** [comment]
It is indeed a long time ago that I looked at this project ...
